### ISSUE TITLE
Cross-Origin Read Blocking (CORB) blocked localhost

### ISSUE THREAD

**Issue by felangga** [MistriHD/Reflect#1]
Hello, I'm running your code for the first time but it stuck on CORB blocking by chrome. I don't know if it server side (cleverbot) or client side (chrome). I managed to disable CORS blocking before with some extension. But this CORB is different. 

Maybe you has any solutions ?
![image](https://user-images.githubusercontent.com/14814984/54073031-cd742c00-42b4-11e9-8dcd-4fc5963f3b76.png)

**Comment by JamsheedMistri** [comment]
Hey, so sorry I didn't see this sooner! For some reason I wasn't watching my own repository.

Are you still having issues? I've been maintaining my own version of Reflect and I'm planning on merging it back with the public version for a v2.0 release soon. In this version, I've completely removed Cleverbot, and I haven't had it in the code for quite a while, so things might have changed with the public Cleverbot API.

**Comment by JamsheedMistri** [comment]
Closing this issue since Cleverbot was removed in v2.0 (f107910f82abcdc9614292fe74af8eabeba68a26). If you're still having CORB issues with the latest version, feel free to re-open the issue.
