### ISSUE TITLE
Voice Commands not working

### ISSUE THREAD

**Issue by unrealb** [MistriHD/Reflect#2]
The voice commands aren't working and I have no idea why. I have a microphone, external sound card, I've put it in the right folder, made some slight changes e.g. changed the language (country) and removed music and when I tried it and accepted the website to use my microphone and said "ok mirror what time is it" nothing happend. Any idead why? Do i have to install something else?

**Comment by JamsheedMistri** [comment]
Hey, I also had this issue when setting up my microphone. Try doing a system sound test for the Raspberry Pi to see if it's a system-level issue first. Is the microphone showing up? Try something like [this](https://iotbytes.wordpress.com/connect-configure-and-test-usb-microphone-and-speaker-with-raspberry-pi/).

If it is showing up, and it's taking input, this is probably a Chromium issue. Open Chromium, go to the settings, and change the input device to your USB microphone. Make sure you enable this for all tabs.

Finally, ensure that the microphone has access to the tab. By default, Chromium denies access to continuously listen through the microphone unless you enable it. On the URL bar, there should be a button with an X through a microphone (or something similar) if the microphone is disabled. Click this to enable the microphone.

Hope this helps! If it doesn't, let me know and we can try a few other things.

**Comment by unrealb** [comment]
First of all, thanks for the fast response!

Yeah, I've tried my microphone on one of this microphone test webistes and it showed that the graph is moving etc.

It may be though, because it's a somewhat old mic, that the quality is not good enough to be understood. When I used the website for the first time I had to accept the microphone use and now it always shows a red dot in the corner. Maybe I should try to buy a newer mic?

**Comment by JamsheedMistri** [comment]
I don't think the microphone quality should matter. Can you go to the JavaScript console in the Chromium Debugger and see what it prints out? It should say "ResponsiveVoice Ready" or something along those lines — does it?

**Comment by unrealb** [comment]
Oh damn I totally forgot the console etc. Well yeah it says Voice support NOT ready. Whoops.
RV: speechSysthesis present but no system voices found (voice.js:93)
RV: Enabling fallback mode                                              (voice.js:94)

Do you know how to get those system voices?

**Comment by JamsheedMistri** [comment]
Check out the API docs for ResponsiveVoice here: https://responsivevoice.org/api/

You mentioned that you:
> changed the language (country)

Perhaps this is why, you might have input an invalid voice. Try changing it back to what it was? If not, generate your own API token and try the version they give on the website.

This may also be relevant: https://askubuntu.com/questions/761975/chromium-is-not-generating-voice

**Comment by unrealb** [comment]
Ok thanks, i'll read a bit. The language change was actually just a translation of date and time and now I use the german newsapi, I think that should not be the problem.

**Comment by unrealb** [comment]
Now I also get some JQuery errors because you seem to use an older version of jquery where the load function still exists... oof

**Comment by JamsheedMistri** [comment]
You can download a new version for free from [here](https://jquery.com/download/)!

**Comment by unrealb** [comment]
I said You! are using the older version i think... because in the code there is the load function but with a new Jquery version it got removed 🤔

**Comment by unrealb** [comment]
I'm getting the 'url.indexof is not a function' error which seems to be pretty common

**Comment by JamsheedMistri** [comment]
Oh, I see. You can change all of the `$(document).load()`s to `$(document).ready()`s. I'll change this soon! Not sure about your `url.indexOf`, that's a built-in JavaScript function. Can you send a screenshot of the exact errors?

**Comment by unrealb** [comment]
![grafik](https://user-images.githubusercontent.com/53619635/62391787-111e4980-b566-11e9-8bc9-cc26834bd37b.png)

If you need more Details i can try

**Comment by unrealb** [comment]
Well if I remove the "solution" from the other website the "indexof" error is gone, nevermind sorry 😄
